services:
  lab5-tools:
    image: ghcr.io/ait-csbe-y28/lab-5-tools:master
    platform: linux/amd64
    container_name: lab5-tools
    depends_on:
      - postgres
      - kafka
    ports:
      - "8070:8070"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8070
      Infrastructure__Persistence__Postgres__Host: postgres
      Infrastructure__Persistence__Postgres__Port: "5432"
      Infrastructure__Persistence__Postgres__Database: lab5_tools
      Infrastructure__Persistence__Postgres__Username: postgres
      Infrastructure__Persistence__Postgres__Password: postgres
      Presentation__Kafka__Host: kafka:9094
      ServiceUrl__BaseUrl: ${SERVICE_URL_BASE_URL:-http://host.docker.internal:5000}
    networks:
      - lab5-tools-network

  postgres:
    image: postgres:16
    container_name: lab5-tools-postgres
    command: postgres -c max_prepared_transactions=100
    environment:
      POSTGRES_DB: lab5_tools
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - lab5-tools-postgres-data:/var/lib/postgresql/data
    networks:
      - lab5-tools-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: lab5-tools-zookeeper
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - lab5-tools-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: lab5-tools-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "8001:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka-data
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://127.0.0.1:8001,INTERNAL://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CREATE_TOPICS: >
        account_created:1:1,
        invoice_created:1:1,
        approval_result:1:1
    volumes:
      - lab5-tools-kafka-data:/kafka-data
    networks:
      - lab5-tools-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: lab5-tools-kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8003:8080"
    volumes:
      - ./src/Presentation/Lab5.Tools.Presentation.Kafka/protos:/schemas/protos:ro
      - ./src/Infrastructure/Lab5.Tools.Infrastructure.Kafka/protos:/schemas/infra-protos:ro
    environment:
      kafka.clusters.0.name: kafka
      kafka.clusters.0.bootstrapServers: kafka:9094
      kafka.clusters.0.defaultKeySerde: ProtobufFile
      kafka.clusters.0.defaultValueSerde: ProtobufFile

      kafka.clusters.0.serde.0.name: ProtobufFile
      kafka.clusters.0.serde.0.properties.protobufFilesDir: /schemas/

      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.account_created: accounts.AccountCreationKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.invoice_created: invoices.InvoiceCreationKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.approval_result: approvals.ApprovalResultKey

      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.account_created: accounts.AccountCreationValue
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.invoice_created: invoices.InvoiceCreationValue
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.approval_result: approvals.ApprovalResultValue
    networks:
      - lab5-tools-network

networks:
  lab5-tools-network:
    name: lab5-tools-network
    driver: bridge

volumes:
  lab5-tools-postgres-data:
  lab5-tools-kafka-data: